// <auto-generated />
using System;
using AccessControl.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706060935_InicialSchema")]
    partial class InicialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cargo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("embedding_json");

                    b.Property<string>("FotoCarnetPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("foto_carnet_path");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("integer")
                        .HasColumnName("localidad_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_empleados");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_cedula");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_codigo");

                    b.HasIndex("LocalidadId")
                        .HasDatabaseName("ix_empleados_localidad_id");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsSistemaAislado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema_aislado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_localidades");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_localidades_nombre");

                    b.ToTable("localidades", (string)null);
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Marcacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CapturaPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("captura_path");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("empleado_id");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("integer")
                        .HasColumnName("localidad_id");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("resultado");

                    b.Property<double>("ScoreSimilitud")
                        .HasColumnType("double precision")
                        .HasColumnName("score_similitud");

                    b.Property<int>("TerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("terminal_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_marcaciones");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("ix_marcaciones_empleado_id");

                    b.HasIndex("LocalidadId")
                        .HasDatabaseName("ix_marcaciones_localidad_id");

                    b.HasIndex("TerminalId")
                        .HasDatabaseName("ix_marcaciones_terminal_id");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_marcaciones_timestamp_utc");

                    b.ToTable("marcaciones", (string)null);
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("integer")
                        .HasColumnName("localidad_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("UbicacionDescripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ubicacion_descripcion");

                    b.HasKey("Id")
                        .HasName("pk_terminales");

                    b.HasIndex("LocalidadId")
                        .HasDatabaseName("ix_terminales_localidad_id");

                    b.ToTable("terminales", (string)null);
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_localidades_localidad_id");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Marcacion", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_marcaciones_empleados_empleado_id");

                    b.HasOne("AccessControl.Domain.Entities.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marcaciones_localidades_localidad_id");

                    b.HasOne("AccessControl.Domain.Entities.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marcaciones_terminales_terminal_id");

                    b.Navigation("Empleado");

                    b.Navigation("Localidad");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Terminal", b =>
                {
                    b.HasOne("AccessControl.Domain.Entities.Localidad", "Localidad")
                        .WithMany("Terminales")
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_terminales_localidades_localidad_id");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("AccessControl.Domain.Entities.Localidad", b =>
                {
                    b.Navigation("Terminales");
                });
#pragma warning restore 612, 618
        }
    }
}
